In [1]:
# import shutil
# # Define the target desktop folder
# desktop_path = os.path.join(os.path.expanduser("~"), "Desktop", "book-recommendation-dataset")

# # Create the folder if it doesn't exist
# os.makedirs(desktop_path, exist_ok=True)

# # Move the downloaded files to the desktop folder
# for file_name in os.listdir(path):
#     full_file_name = os.path.join(path, file_name)
#     if os.path.isfile(full_file_name):
#         shutil.move(full_file_name, desktop_path)

# print("Dataset files have been saved to:", desktop_path)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [38]:
book=pd.read_csv("book-recommendation-dataset/Books.csv")
users=pd.read_csv("book-recommendation-dataset/Users.csv")
ratings=pd.read_csv("book-recommendation-dataset/Ratings.csv")

/var/folders/hz/ljttb8jn1_76tktqc42tnpzm0000gn/T/ipykernel_876/1354750841.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  book=pd.read_csv("book-recommendation-dataset/Books.csv")

In [39]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [40]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [41]:
ratings.duplicated().sum()

0

In [42]:
users.duplicated().sum()

0

In [43]:
book.duplicated().sum()

0

In [44]:
book.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [13]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [14]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [45]:
book['Year-Of-Publication'].value_counts().sort_values()

Year-Of-Publication
2037        1
2011        1
2038        1
1938        1
1906        1
        ...
1998    12116
2000    13373
1999    13414
2001    13715
2002    13903
Name: count, Length: 202, dtype: int64

## Popularity based recommender system

In [46]:
ratings.merge(book,on="ISBN").shape

(1031136, 10)

In [47]:
ratings_with_name=ratings.merge(book,on="ISBN")

In [48]:
ratings_with_name

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276688,0517145553,0,Mostly Harmless,Douglas Adams,1995,Random House Value Pub,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...
1031132,276688,1575660792,7,Gray Matter,Shirley Kennett,1996,Kensington Publishing Corporation,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...
1031133,276690,0590907301,0,Triplet Trouble and the Class Trip (Triplet Tr...,Debbie Dadey,1997,Apple,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...
1031134,276704,0679752714,0,A Desert of Pure Feeling (Vintage Contemporaries),Judith Freeman,1997,Vintage Books USA,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...
1031135,276704,0806917695,5,Perplexing Lateral Thinking Puzzles: Scholasti...,Paul Sloane,1997,Sterling Publishing,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...

In [50]:
#to get how many times a book was rated
num_rating_df=ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating':'num_ratings'},inplace=True)

In [51]:
num_rating_df

                                               Book-Title  num_ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [52]:
#to get the average of how many times that book was rated
avg_rating_df=ratings_with_name.groupby('Book-Title').mean(numeric_only=True)['Book-Rating'].reset_index()
avg_rating_df.rename(columns={'Book-Rating':'avg_ratings'},inplace=True)

In [53]:
avg_rating_df

                                               Book-Title  avg_ratings
0        A Light in the Storm: The Civil War Diary of ...     2.250000
1                                   Always Have Popsicles     0.000000
2                    Apple Magic (The Collector's series)     0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...     8.000000
4        Beyond IBM: Leadership Marketing and Finance ...     0.000000
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.     0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.     5.250000
241068                                Ã?Â?sterlich leben.     7.000000
241069                              Ã?Â?stlich der Berge.     2.666667
241070                                  Ã?Â?thique en toc     4.000000

[241071 rows x 2 columns]

In [54]:
popular_df = num_rating_df.merge(avg_rating_df,on='Book-Title')

In [55]:
#take only those books which have 250 ratings
popular_df = popular_df[popular_df['num_ratings']>250].sort_values('avg_ratings',ascending=False)

In [56]:
popular_df = num_rating_df.merge(avg_rating_df,on='Book-Title')

In [57]:
popular_df

,Book-Title,num_ratings,avg_ratings
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [58]:
popular_df.merge(book,on='Book-Title')#some books have same title (see 0&1) and but different isbn because different publication year
#so drop duplicates since rarings is same for all books

,Book-Title,num_ratings,avg_ratings,ISBN,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000,0590567330,Karen Hesse,1999,Hyperion Books for Children,http://images.amazon.com/images/P/0590567330.0...,http://images.amazon.com/images/P/0590567330.0...,http://images.amazon.com/images/P/0590567330.0...
1,Always Have Popsicles,1,0.000000,0964147726,Rebecca Harvin,1994,Rebecca L. Harvin,http://images.amazon.com/images/P/0964147726.0...,http://images.amazon.com/images/P/0964147726.0...,http://images.amazon.com/images/P/0964147726.0...
2,Apple Magic (The Collector's series),1,0.000000,0942320093,Martina Boudreau,1984,Amer Cooking Guild,http://images.amazon.com/images/P/0942320093.0...,http://images.amazon.com/images/P/0942320093.0...,http://images.amazon.com/images/P/0942320093.0...
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000,0310232546,Nancy N. Rue,2001,Zonderkidz,http://images.amazon.com/images/P/0310232546.0...,http://images.amazon.com/images/P/0310232546.0...,http://images.amazon.com/images/P/0310232546.0...
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000,0962295701,Lou Mobley,1989,"Teleonet, Incorporated",http://images.amazon.com/images/P/0962295701.0...,http://images.amazon.com/images/P/0962295701.0...,http://images.amazon.com/images/P/0962295701.0...
...,...,...,...,...,...,...,...,...,...,...
270291,Ã?Â?lpiraten.,2,0.000000,3499232499,Janwillem van de Wetering,2002,Rowohlt Tb.,http://images.amazon.com/images/P/3499232499.0...,http://images.amazon.com/images/P/3499232499.0...,http://images.amazon.com/images/P/3499232499.0...
270292,Ã?Â?rger mit Produkt X. Roman.,4,5.250000,325721538X,Joan Aiken,1987,Diogenes Verlag,http://images.amazon.com/images/P/325721538X.0...,http://images.amazon.com/images/P/325721538X.0...,http://images.amazon.com/images/P/325721538X.0...
270293,Ã?Â?sterlich leben.,1,7.000000,3451274973,Anselm GrÃ?Â¼n,2001,"Herder, Freiburg",http://images.amazon.com/images/P/3451274973.0...,http://images.amazon.com/images/P/3451274973.0...,http://images.amazon.com/images/P/3451274973.0...
270294,Ã?Â?stlich der Berge.,3,2.666667,3442725739,David Guterson,2000,btb,http://images.amazon.com/images/P/3442725739.0...,http://images.amazon.com/images/P/3442725739.0...,http://images.amazon.com/images/P/3442725739.0...
270295,Ã?Â?thique en toc,2,4.000000,2842192508,Didier Daeninckx,1998,Baleine,http://images.amazon.com/images/P/2842192508.0...,http://images.amazon.com/images/P/2842192508.0...,http://images.amazon.com/images/P/2842192508.0...

In [59]:
popular_df = popular_df.merge(book,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Image-URL-S','Image-URL-M','Image-URL-L','num_ratings','avg_ratings']]

In [60]:
popular_df['Image-URL-S'][0]
popular_df['Book-Title'][0]

' A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)'

## Collaborative Filtering based recommender system

In [61]:
#how many users gave the ratings and how many number of times

ratings_with_name.groupby('User-ID').count()['Book-Rating']

User-ID
2          1
8         17
9          3
10         1
12         1
          ..
278846     1
278849     4
278851    23
278852     1
278854     8
Name: Book-Rating, Length: 92106, dtype: int64

In [62]:
#fetch only those users who have give more than 200 ratings
x = ratings_with_name.groupby('User-ID').count()['Book-Rating']>200
knowlegeable_users = x[x].index

In [63]:
x[x]

User-ID
254       True
2276      True
2766      True
2977      True
3363      True
          ...
274308    True
275970    True
277427    True
277639    True
278418    True
Name: Book-Rating, Length: 811, dtype: bool

In [64]:
knowlegeable_users

Index([   254,   2276,   2766,   2977,   3363,   4017,   4385,   6251,   6323,
         6543,
       ...
       271705, 273979, 274004, 274061, 274301, 274308, 275970, 277427, 277639,
       278418],
      dtype='int64', name='User-ID', length=811)

In [65]:
filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(knowlegeable_users)]

In [66]:
#get only those books which have more than 50 ratings.

In [67]:
y=filtered_rating.groupby('Book-Title').count()['Book-Rating']>=50
famous_books = y[y].index

In [68]:
final_ratings = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [69]:
pt = final_ratings.pivot_table(index='Book-Title',columns='User-ID',values='Book-Rating')

In [70]:
pt.fillna(0,inplace=True)

In [71]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [72]:
#to find the distance from the book to all the other book including that book itself(treated as a nd plot)
from sklearn.metrics.pairwise import cosine_similarity
similarity_score = cosine_similarity(pt)

In [73]:
similarity_score.shape

(706, 706)

In [74]:
similarity_score[0]#gives the similarity scores of the first book and all the userid

array([1.        , 0.10255025, 0.01220856, 0.        , 0.05367224,
       0.02774901, 0.08216491, 0.13732869, 0.03261686, 0.03667591,
       0.02322418, 0.06766487, 0.02083978, 0.09673735, 0.13388865,
       0.08303112, 0.11153543, 0.05100411, 0.02517784, 0.11706383,
       0.        , 0.14333793, 0.07847534, 0.06150451, 0.08723968,
       0.        , 0.07009814, 0.13658681, 0.07600328, 0.12167134,
       0.00768046, 0.01473221, 0.        , 0.07965814, 0.04522617,
       0.01556271, 0.09495938, 0.0182307 , 0.02610465, 0.07984012,
       0.11679969, 0.0569124 , 0.08354155, 0.08471898, 0.08785938,
       0.05491435, 0.0548505 , 0.27026514, 0.09779123, 0.06016046,
       0.08958835, 0.06748675, 0.        , 0.04468098, 0.01920872,
       0.        , 0.05629067, 0.00557964, 0.07877059, 0.05219479,
       0.18908177, 0.        , 0.01240656, 0.02984572, 0.04279502,
       0.12680125, 0.16566735, 0.        , 0.13357242, 0.06615478,
       0.        , 0.        , 0.        , 0.10968075, 0.02806606,
       0.04521795, 0.02613277, 0.06876131, 0.01331627, 0.10519138,
       0.03349457, 0.01363458, 0.23669374, 0.        , 0.10397941,
       0.06167753, 0.14176273, 0.11661083, 0.08331012, 0.00850895,
       0.06715433, 0.        , 0.15850821, 0.0328052 , 0.01068915,
       0.02579782, 0.02114859, 0.02687779, 0.02175821, 0.        ,
       0.01601663, 0.12114266, 0.04768603, 0.05819184, 0.06510722,
       0.        , 0.0476705 , 0.05273165, 0.0281001 , 0.06524573,
       0.02116345, 0.02097868, 0.07422249, 0.01752778, 0.03734567,
       0.        , 0.01579666, 0.11039448, 0.16527277, 0.15514319,
       0.06237454, 0.08139489, 0.05655414, 0.07458203, 0.03771888,
       0.0593633 , 0.02955369, 0.03355603, 0.04734093, 0.01006643,
       0.01671982, 0.07258935, 0.        , 0.        , 0.        ,
       0.02428501, 0.03067819, 0.0997498 , 0.        , 0.01690152,
       0.02410862, 0.0281084 , 0.        , 0.        , 0.01812877,
       0.02880827, 0.        , 0.05995157, 0.02127671, 0.1034119 ,
       0.02766748, 0.10684795, 0.09898722, 0.14145186, 0.05007429,
       0.09428289, 0.01411249, 0.        , 0.07835976, 0.00882242,
       0.04515898, 0.        , 0.01281412, 0.04003334, 0.07477661,
       0.01217906, 0.01887393, 0.02667484, 0.01432864, 0.14702847,
       0.06087282, 0.02578321, 0.02741876, 0.        , 0.14909595,
       0.05606788, 0.        , 0.03199916, 0.03643817, 0.        ,
       0.01962921, 0.22222254, 0.01515845, 0.09673268, 0.02190023,
       0.02013549, 0.05400331, 0.07262017, 0.01111637, 0.03649872,
       0.05994664, 0.        , 0.14691167, 0.02086005, 0.10359635,
       0.09794375, 0.06609997, 0.12871083, 0.08992739, 0.01147457,
       0.02460165, 0.        , 0.18049207, 0.05141892, 0.0477174 ,
       0.10849696, 0.13278139, 0.05915288, 0.05372984, 0.034785  ,
       0.        , 0.09203039, 0.06388401, 0.04773328, 0.15570975,
       0.08420691, 0.12338217, 0.0878469 , 0.08205945, 0.12177532,
       0.02433703, 0.00272862, 0.        , 0.        , 0.03671505,
       0.15280984, 0.0370943 , 0.07458136, 0.09746697, 0.05416091,
       0.10266993, 0.07574414, 0.06426526, 0.0360174 , 0.01559752,
       0.02033559, 0.02463593, 0.        , 0.03349154, 0.02135369,
       0.0190337 , 0.06806265, 0.02032116, 0.11784706, 0.07839488,
       0.08422558, 0.        , 0.02040796, 0.        , 0.04698246,
       0.08294513, 0.13974514, 0.01234525, 0.13510608, 0.07423489,
       0.11841889, 0.04930091, 0.01621668, 0.02633023, 0.04815972,
       0.01959826, 0.10174253, 0.13257638, 0.        , 0.0551027 ,
       0.0186115 , 0.        , 0.04504598, 0.03482459, 0.16503292,
       0.08466191, 0.06795353, 0.02987653, 0.        , 0.        ,
       0.08781993, 0.07885279, 0.04799058, 0.01467964, 0.02123837,
       0.04549923, 0.08673969, 0.00885998, 0.02880637, 0.02022145,
       0.02414122, 0.12548312, 0.        , 0.02482518, 0.06520606,
       0.        , 0.0606983 , 0.01177824, 0.13974105, 0.01978844,
       0.01260824, 0.08608601, 0.04433883, 0.02943085, 0.02242496,
       0.06541868, 0.07866868, 0.14281399, 0.11979305, 0.01858409,
       0.13445377, 0.04809338, 0.09790644, 0.        , 0.17415731,
       0.07437756, 0.        , 0.12389065, 0.01042391, 0.02580849,
       0.        , 0.0895139 , 0.04005551, 0.19182231, 0.02267512,
       0.01730347, 0.03054044, 0.07008822, 0.10084626, 0.10467615,
       0.01683462, 0.12468283, 0.10266459, 0.03549836, 0.02667484,
       0.07652765, 0.08474056, 0.01831977, 0.02177482, 0.15293362,
       0.        , 0.        , 0.01063251, 0.02153089, 0.02946443,
       0.        , 0.02076783, 0.01194825, 0.00953675, 0.2067554 ,
       0.01554292, 0.0390266 , 0.06681046, 0.09014973, 0.05914735,
       0.06206857, 0.        , 0.02005959, 0.07843566, 0.16337845,
       0.07161075, 0.        , 0.14595258, 0.07561631, 0.02939738,
       0.04779629, 0.01807238, 0.11362722, 0.09791273, 0.07999693,
       0.08912337, 0.10941777, 0.        , 0.02115842, 0.0600393 ,
       0.01797154, 0.05755408, 0.02166863, 0.09754449, 0.13107652,
       0.        , 0.06829904, 0.09132922, 0.        , 0.02781406,
       0.01533368, 0.06113179, 0.01757286, 0.02471294, 0.0180158 ,
       0.11789806, 0.06468143, 0.13904191, 0.        , 0.06671644,
       0.        , 0.        , 0.05762086, 0.02266096, 0.00844876,
       0.02297481, 0.07136276, 0.15305514, 0.06039874, 0.        ,
       0.08996912, 0.01545947, 0.10135299, 0.        , 0.01676344,
       0.        , 0.0502188 , 0.16041182, 0.        , 0.13439733,
       0.12508514, 0.02329035, 0.0198727 , 0.01105674, 0.02548034,
       0.00896044, 0.08246122, 0.01902896, 0.07025003, 0.0216367 ,
       0.12822982, 0.09998772, 0.08642895, 0.06355197, 0.02883024,
       0.04335826, 0.0470659 , 0.05223733, 0.        , 0.08982751,
       0.00875634, 0.09923542, 0.10228551, 0.        , 0.12307492,
       0.01758929, 0.02028125, 0.1033827 , 0.13028171, 0.08988894,
       0.09005001, 0.05332049, 0.08033436, 0.04597795, 0.06139888,
       0.02300709, 0.02304904, 0.06523041, 0.01915363, 0.        ,
       0.04542766, 0.        , 0.        , 0.05261954, 0.01317088,
       0.        , 0.        , 0.0485931 , 0.0734819 , 0.10354481,
       0.01718807, 0.09919937, 0.08091989, 0.00358835, 0.04757132,
       0.11122765, 0.05143481, 0.0566614 , 0.        , 0.06087719,
       0.10800615, 0.        , 0.07554686, 0.        , 0.13644384,
       0.04796763, 0.16104067, 0.        , 0.01759864, 0.05438295,
       0.        , 0.08100801, 0.13090711, 0.00581844, 0.07150547,
       0.05428487, 0.06143184, 0.05161653, 0.1951182 , 0.1149488 ,
       0.06513047, 0.06401961, 0.        , 0.        , 0.10853662,
       0.11400426, 0.0463925 , 0.01825277, 0.        , 0.01195201,
       0.21057744, 0.05809707, 0.04349156, 0.02646256, 0.07276403,
       0.05264857, 0.07242165, 0.06790898, 0.01626564, 0.02431809,
       0.02093565, 0.13617057, 0.11784149, 0.08588206, 0.09284352,
       0.11277297, 0.06868983, 0.08200947, 0.13369059, 0.        ,
       0.19972625, 0.02286207, 0.0806288 , 0.        , 0.05756015,
       0.06738056, 0.        , 0.19656288, 0.06306426, 0.03499381,
       0.06123119, 0.09596456, 0.02180168, 0.02317515, 0.06476149,
       0.07052241, 0.08280452, 0.1700872 , 0.07213921, 0.01172201,
       0.08541218, 0.17990898, 0.08007284, 0.01739625, 0.16728777,
       0.26396194, 0.1840891 , 0.05600273, 0.04133586, 0.06911015,
       0.14456847, 0.22626397, 0.19208896, 0.0239334 , 0.20025064,
       0.01507653, 0.05144282, 0.1233368 , 0.1420166 , 0.02472079,
       0.08563805, 0.02363426, 0.12794024, 0.01083153, 0.07352436,
       0.09532519, 0.03421895, 0.07194212, 0.02297079, 0.15344079,
       0.08856302, 0.        , 0.        , 0.01878656, 0.09772942,
       0.04404359, 0.15211972, 0.0152225 , 0.10307399, 0.05715789,
       0.04600056, 0.06303899, 0.06572303, 0.14421331, 0.08272478,
       0.        , 0.04203701, 0.02276077, 0.17381829, 0.01909967,
       0.16000268, 0.14681486, 0.        , 0.05940546, 0.07725115,
       0.07464763, 0.06546696, 0.07021577, 0.18921368, 0.02494136,
       0.01705027, 0.05437622, 0.04932819, 0.        , 0.11445399,
       0.08001595, 0.12858515, 0.02306658, 0.06129105, 0.02090769,
       0.04550867, 0.1026659 , 0.10725982, 0.0260534 , 0.00173709,
       0.0987294 , 0.08077482, 0.02159226, 0.01614275, 0.0208464 ,
       0.09797466, 0.01906731, 0.18571699, 0.05344577, 0.18925314,
       0.05894189, 0.01488161, 0.1202478 , 0.09840359, 0.01048126,
       0.10596224, 0.07617195, 0.0805439 , 0.        , 0.23299389,
       0.01073642, 0.13573542, 0.04578552, 0.14440017, 0.        ,
       0.12522954, 0.0645501 , 0.02817522, 0.14445559, 0.01721045,
       0.09508161, 0.0517902 , 0.18410818, 0.08704224, 0.10990764,
       0.10850377, 0.03954865, 0.0383631 , 0.02463491, 0.07845405,
       0.03455548, 0.03007681, 0.02484076, 0.04223674, 0.14444517,
       0.12340234, 0.01510201, 0.0284437 , 0.02132016, 0.07391778,
       0.08904276, 0.15893871, 0.06947574, 0.01060787, 0.        ,
       0.09993169, 0.05711356, 0.09488374, 0.00948943, 0.13365876,
       0.05794064, 0.        , 0.06721284, 0.02066998, 0.        ,
       0.01839428, 0.        , 0.12655364, 0.08418288, 0.09095705,
       0.00730589, 0.08143881, 0.        , 0.04218803, 0.08392849,
       0.07785801, 0.        , 0.07151794, 0.02407593, 0.01635126,
       0.03734567, 0.05237227, 0.01140169, 0.00968725, 0.12530648,
       0.00909905, 0.05864096, 0.01769644, 0.12110367, 0.07347567,
       0.04316046])

In [75]:
np.where(pt.index=='Zoya')[0][0]#gives the index of the book

704

In [76]:
#distances = similarity_score[index]find the similarity scores of that book whose index is some x.
sorted(list(enumerate(similarity_score[0])))#get the all the similarity scores of book of index 0 with bookid.
#But sorting will be based on index
#but sorting should be based on the similarity_scores.so,
sorted(list(enumerate(similarity_score[0])),key=lambda x:x[1])#get in scending but we want in descending order.
sorted(list(enumerate(similarity_score[0])),key=lambda x:x[1],reverse=True)#but first one is the similarity score of the book with itself
sorted(list(enumerate(similarity_score[0])),key=lambda x:x[1],reverse=True)[1:6]#pick top 6 recommendation

[(47, 0.2702651417103732),
 (545, 0.2639619371123497),
 (82, 0.23669374347400993),
 (634, 0.23299389358170394),
 (551, 0.2262639743141286)]

In [77]:
pt.index

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Day Late and a Dollar Short', 'A Fine Balance',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='Book-Title', length=706)

In [78]:
def recommend(book_name):
    #index_fetch
    index=np.where(pt.index==book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_score[index])),key=lambda x:x[1],reverse=True)[1:6]

    for i in similar_items:
      print(pt.index[i[0]])

In [79]:
popular_df

,Book-Title,Book-Author,Image-URL-S,Image-URL-M,Image-URL-L,num_ratings,avg_ratings
0,A Light in the Storm: The Civil War Diary of ...,Karen Hesse,http://images.amazon.com/images/P/0590567330.0...,http://images.amazon.com/images/P/0590567330.0...,http://images.amazon.com/images/P/0590567330.0...,4,2.250000
1,Always Have Popsicles,Rebecca Harvin,http://images.amazon.com/images/P/0964147726.0...,http://images.amazon.com/images/P/0964147726.0...,http://images.amazon.com/images/P/0964147726.0...,1,0.000000
2,Apple Magic (The Collector's series),Martina Boudreau,http://images.amazon.com/images/P/0942320093.0...,http://images.amazon.com/images/P/0942320093.0...,http://images.amazon.com/images/P/0942320093.0...,1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",Nancy N. Rue,http://images.amazon.com/images/P/0310232546.0...,http://images.amazon.com/images/P/0310232546.0...,http://images.amazon.com/images/P/0310232546.0...,1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,Lou Mobley,http://images.amazon.com/images/P/0962295701.0...,http://images.amazon.com/images/P/0962295701.0...,http://images.amazon.com/images/P/0962295701.0...,1,0.000000
...,...,...,...,...,...,...,...
270291,Ã?Â?lpiraten.,Janwillem van de Wetering,http://images.amazon.com/images/P/3499232499.0...,http://images.amazon.com/images/P/3499232499.0...,http://images.amazon.com/images/P/3499232499.0...,2,0.000000
270292,Ã?Â?rger mit Produkt X. Roman.,Joan Aiken,http://images.amazon.com/images/P/325721538X.0...,http://images.amazon.com/images/P/325721538X.0...,http://images.amazon.com/images/P/325721538X.0...,4,5.250000
270293,Ã?Â?sterlich leben.,Anselm GrÃ?Â¼n,http://images.amazon.com/images/P/3451274973.0...,http://images.amazon.com/images/P/3451274973.0...,http://images.amazon.com/images/P/3451274973.0...,1,7.000000
270294,Ã?Â?stlich der Berge.,David Guterson,http://images.amazon.com/images/P/3442725739.0...,http://images.amazon.com/images/P/3442725739.0...,http://images.amazon.com/images/P/3442725739.0...,3,2.666667
270295,Ã?Â?thique en toc,Didier Daeninckx,http://images.amazon.com/images/P/2842192508.0...,http://images.amazon.com/images/P/2842192508.0...,http://images.amazon.com/images/P/2842192508.0...,2,4.000000

In [80]:
import pickle
# pickle.dump(popular_df,open('popular.pkl','wb'))

In [48]:
pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(books,open('books.pkl','wb'))
pickle.dump(similarity_score,open('similarity_scores.pkl','wb'))